@startuml

title __AURORA's Class Diagram__\n

  namespace  {
    namespace ndi.augusttheodor.aurora {
      class indi.augusttheodor.aurora.AuroraApplication {
          {static} + context : Context
          {static} + httpPackage : OkHttpPackage
          {static} + image_loader : ImageLoader
          {static} + long_memory_opt : DisplayImageOptions
          {static} + options : Builder
          {static} + r_long_rect_opt : DisplayImageOptions
          {static} + short_memory_opt : DisplayImageOptions
          {static} + userID : String
          {static} + userNick : String
          {static} + DownloadImage()
          {static} + autoEllipsis()
          {static} + dp2px()
          {static} + getDpHeight()
          + onCreate()
          + onResponse()
          {static} + pickerPic()
          {static} + pickerRectangleImage()
          {static} + pickerRoundImage()
          {static} + setImgSpan()
          {static} + setImgSpanOld()
          {static} + shiftColor()
          {static} + shiftImg()
          {static} + shiftList()
          {static} + shiftString()
          {static} + shiftTime()
          - initImageLoader()
      }
    }
  }
  

  namespace  {
    namespace ndi.augusttheodor.aurora {
      class indi.augusttheodor.aurora.AuroraApplication.Constants {
          {static} + Article : String
          {static} + Comment : String
          {static} + Group : String
          {static} + Summary : String
          {static} + Transmit : String
          {static} + Trend : String
          {static} + Type_Private : String
          {static} + Type_Protected : String
          {static} + Type_Public : String
          {static} + User : String
      }
    }
  }
  

  indi.augusttheodor.aurora.AuroraApplication .up.|> indi.augusttheodor.aurora.inter.HttpInterface
  indi.augusttheodor.aurora.AuroraApplication -up-|> com.orm.SugarApp
  indi.augusttheodor.aurora.AuroraApplication +-down- indi.augusttheodor.aurora.AuroraApplication.Constants


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
