@startuml

title __INTER's Class Diagram__\n


    namespace indi.augusttheodor.aurora {
      namespace inter {
        class indi.augusttheodor.aurora.inter.AdapterItems {
            - items : List<T>
            + AdapterItems()
            + add()
            + add()
            + clear()
            + getItems()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        abstract class indi.augusttheodor.aurora.inter.AuroraImageClickableSpan {
            + AuroraImageClickableSpan()
            {abstract} + onClick()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        interface indi.augusttheodor.aurora.inter.HttpInterface {
            {abstract} + onResponse()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        abstract class indi.augusttheodor.aurora.inter.OriginalArticleActivity {
            + article_id : String
            + detector : GestureDetector
            + type : String
            + view : View
            + view_pager : ViewPager2
            + dispatchTouchEvent()
            + isHideKeyboard()
            + onCheckedChanged()
            + onClick()
            + onFocusChange()
            + onLongClick()
            + onMenuItemClick()
            + onResponse()
            + refreshMenu()
            + writeMeta()
            # onCreate()
            - setIds()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        interface indi.augusttheodor.aurora.inter.RecyclerViewListenerInterface {
            {abstract} + onNext()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        interface indi.augusttheodor.aurora.inter.SearchInter {
            {abstract} + clear()
            {abstract} + setKeywordNext()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        abstract class indi.augusttheodor.aurora.inter.ViewPager2Gesture {
            + ids : HashMap<View, Integer>
            + view_pager : ViewPager2
            + onDown()
            + onFling()
            + onLongPress()
            + onScroll()
            + onShowPress()
            + onSingleTapUp()
            # onCreate()
        }
      }
    }
  
  


    namespace indi.augusttheodor.aurora {
      namespace inter {
        abstract class indi.augusttheodor.aurora.inter.ViewPager2LayoutAdapter {
            + fragment_list : ArrayList<Fragment>
            + ViewPager2LayoutAdapter()
            + createFragment()
            + getItemCount()
        }
      }
    }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
